title: "WILD WAFFLE"
description: "Solo Creator"
theme: minima
minima:
  skin: auto

plugins:
  - jekyll-feed

feed:
  path: feed.xml

author:
  name: "Created by WAFFLE"

nav:
  - title: "Me"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Resources"
    url: "/resources/"
  - title: "RSS"
    url: "/feed.xml"

social_links:
  - name: "YouTube"
    url: "https://www.youtube.com/@wildwaffleofficial"
  - name: "Telegram"
    url: "https://t.me/wafflewithin"
  - name: "Apple Podcast"
    url: "https://podcasts.apple.com/us/podcast/woven-waffle/id1864634309"
