title: "WILD WAFFLE"
description: "Creator blog"
theme: minima
minima:
  skin: auto

author:
  name: "by WAFFLE"

# Навигация
nav:
  - title: "About"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"

social_links:
  - name: "YouTube"
    url: "https://youtube.com/yourchannel"
  - name: "Telegram"
    url: "https://t.me/yourtelegram"
  - name: "Podcast"
    url: "https://podcast-link"