title: WILDWAFFLE
logo: /assets/img/avatar.png
# email: 
description: Creator blog
favicon: true
color-scheme: auto

theme: jekyll-theme-minimalistic

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: YouTube
    icon: <i class="fa-brands fa-youtube"></i>
    link: https://youtube.com/@wildwaffleofficial
  - name: Telegram
    icon: <i class="fa-brands fa-telegram"></i>
    link: https://t.me/wafflewithin
  # - name: Podcast
  #   icon: <i class="fa-solid fa-podcast"></i>
  #   link: https://podcasts.apple.com/ru/channel/

# navigation:
#   - name: Readme
#     link: ./index.html
#     # sublist:
#     #   - name: Image
#     #     link: ./index.html#small-image
#   - name: Another Page
#     link: ./another-page.html