title: "WILD WAFFLE"
description: "Solo Creator | Filmmaker | Comic Artist | Game Developer"
theme: minima
minima:
  skin: auto

author:
  name: "by WAFFLE"
  email: "artyom.ognyov@gmail.com"

nav:
  - title: "Me"
    url: "/about/"
  - title: "Projects"
    url: "/projects/"
  - title: "Resources"
    url: "/resources/"

social_links:
  - name: "YouTube"
    url: "https://www.youtube.com/@wildwaffleofficial"
  - name: "Telegram"
    url: "https://t.me/wafflewithin"
  # - name: "Podcast"
  #   url: "https://podcast-link"